apiVersion: v1
kind: Secret
metadata:
  name: incident-secret
type: Opaque
stringData:
  DB_DSN: "postgres://oncall:oncall@postgres:5432/oncall?sslmode=disable&search_path=incident"
  REDIS_ADDR: "redis:6379"
  RABBITMQ_URL: "amqp://oncall:oncall@rabbitmq:5672/"
  ADMIN_API_KEY: "change-me"
